import { XName, XNamespace } from 'ltxmlts';

export class P14 {
    static readonly namespace: XNamespace = XNamespace.get("http://schemas.microsoft.com/office/powerpoint/2010/main");

    static readonly bmk: XName = P14.namespace.getName("bmk");
    static readonly bmkLst: XName = P14.namespace.getName("bmkLst");
    static readonly bmkTgt: XName = P14.namespace.getName("bmkTgt");
    static readonly bounceEnd: XName = P14.namespace.getName("bounceEnd");
    static readonly bwMode: XName = P14.namespace.getName("bwMode");
    static readonly cNvContentPartPr: XName = P14.namespace.getName("cNvContentPartPr");
    static readonly cNvPr: XName = P14.namespace.getName("cNvPr");
    static readonly conveyor: XName = P14.namespace.getName("conveyor");
    static readonly creationId: XName = P14.namespace.getName("creationId");
    static readonly doors: XName = P14.namespace.getName("doors");
    static readonly dur: XName = P14.namespace.getName("dur");
    static readonly extLst: XName = P14.namespace.getName("extLst");
    static readonly fade: XName = P14.namespace.getName("fade");
    static readonly ferris: XName = P14.namespace.getName("ferris");
    static readonly flash: XName = P14.namespace.getName("flash");
    static readonly flip: XName = P14.namespace.getName("flip");
    static readonly flythrough: XName = P14.namespace.getName("flythrough");
    static readonly gallery: XName = P14.namespace.getName("gallery");
    static readonly glitter: XName = P14.namespace.getName("glitter");
    static readonly honeycomb: XName = P14.namespace.getName("honeycomb");
    static readonly laserTraceLst: XName = P14.namespace.getName("laserTraceLst");
    static readonly media: XName = P14.namespace.getName("media");
    static readonly modId: XName = P14.namespace.getName("modId");
    static readonly nvContentPartPr: XName = P14.namespace.getName("nvContentPartPr");
    static readonly nvPr: XName = P14.namespace.getName("nvPr");
    static readonly pan: XName = P14.namespace.getName("pan");
    static readonly pauseEvt: XName = P14.namespace.getName("pauseEvt");
    static readonly playEvt: XName = P14.namespace.getName("playEvt");
    static readonly presetBounceEnd: XName = P14.namespace.getName("presetBounceEnd");
    static readonly prism: XName = P14.namespace.getName("prism");
    static readonly resumeEvt: XName = P14.namespace.getName("resumeEvt");
    static readonly reveal: XName = P14.namespace.getName("reveal");
    static readonly ripple: XName = P14.namespace.getName("ripple");
    static readonly section: XName = P14.namespace.getName("section");
    static readonly sectionLst: XName = P14.namespace.getName("sectionLst");
    static readonly seekEvt: XName = P14.namespace.getName("seekEvt");
    static readonly showEvtLst: XName = P14.namespace.getName("showEvtLst");
    static readonly shred: XName = P14.namespace.getName("shred");
    static readonly sldId: XName = P14.namespace.getName("sldId");
    static readonly sldIdLst: XName = P14.namespace.getName("sldIdLst");
    static readonly stopEvt: XName = P14.namespace.getName("stopEvt");
    static readonly _switch: XName = P14.namespace.getName("switch");
    static readonly tracePt: XName = P14.namespace.getName("tracePt");
    static readonly tracePtLst: XName = P14.namespace.getName("tracePtLst");
    static readonly triggerEvt: XName = P14.namespace.getName("triggerEvt");
    static readonly trim: XName = P14.namespace.getName("trim");
    static readonly vortex: XName = P14.namespace.getName("vortex");
    static readonly warp: XName = P14.namespace.getName("warp");
    static readonly wheelReverse: XName = P14.namespace.getName("wheelReverse");
    static readonly window: XName = P14.namespace.getName("window");
    static readonly xfrm: XName = P14.namespace.getName("xfrm");
}
